FROM php:7.0-apache
RUN docker-php-ext-install mysqli
COPY /webapp/php.ini /usr/local/etc/php/  
COPY /webapp/css/ /var/www/html/css/
COPY /webapp/images/ /var/www/html/images/
COPY /webapp/js/ /var/www/html/js/
COPY /webapp/about.php /var/www/html/
COPY /webapp/account.php /var/www/html/
COPY /webapp/admin.php /var/www/html/
COPY /webapp/admin-update.php /var/www/html/
COPY /webapp/bolt.sql /var/www/html/
COPY /webapp/bolt-new-phpmyadmin.sql /var/www/html/
COPY /webapp/php.ini /var/www/html/
COPY /webapp/cart.php /var/www/html/
COPY /webapp/config.php /var/www/html/
COPY /webapp/contact.php /var/www/html/
COPY /webapp/humans.txt /var/www/html/
COPY /webapp/index.php /var/www/html/
COPY /webapp/insert.php /var/www/html/
COPY /webapp/login.php /var/www/html/
COPY /webapp/logout.php /var/www/html/
COPY /webapp/orders.php /var/www/html/
COPY /webapp/products.php /var/www/html/
COPY /webapp/orders-update.php /var/www/html/
COPY /webapp/register.php /var/www/html/
COPY /webapp/robots.txt /var/www/html/
COPY /webapp/success.php /var/www/html/
COPY /webapp/update.php /var/www/html/
COPY /webapp/update-cart.php /var/www/html/
COPY /webapp/verify.php /var/www/html/
